### ISSUE TITLE
Aiming and other improvements + new setting: "manual_attack_always"

### ISSUE THREAD

**Issue by 4512369781** [smilz0/Left4Bots#55]
Hi, I finish it, after some testing, I think there shouldn't be much of a problem.

This allows bots to aim without having to freeze them, so it doesn't affect movement. and bots can always look at the target without shaking their head.
[left4bots_afterload_aim.zip](https://github.com/smilz0/Left4Bots/files/13208554/left4bots_afterload_aim.zip)

**Comment by smilz0** [comment]
Hey, can you add me on steam? I want to ask something.

**Comment by 4512369781** [comment]
> Hey, can you add me on steam? I want to ask something.

I sent a friend request, my English is not very good and due to the time difference, the reply may be a bit slow.

**Comment by 4512369781** [comment]
Hi, I updated some things and tested them too, and they look better than the first version.
[left4bots_afterload_aim.zip](https://github.com/smilz0/Left4Bots/files/13285013/left4bots_afterload_aim.zip)

**Comment by 4512369781** [comment]
update:
> fix bots rotating when pick up item
> adjust shove jockey/hunter

[left4bots_afterload_aim.zip](https://github.com/smilz0/Left4Bots/files/13301053/left4bots_afterload_aim.zip)

**Comment by smilz0** [comment]
Thank you man, i like this. I also changed it so your aiming function is always active, not only while executing orders, but i will probably add a setting to enable/disable this when i merge the code.
Btw i made some changes to the code of the entire addon to try optimize it more so your code needed some changes too in order to work. Here is the updated version.
[left4bots_afterload_new.zip](https://github.com/smilz0/Left4Bots/files/13309996/left4bots_afterload_new.zip)
I will test it a bit more and i will merge it when i can. Thx!

**Comment by 4512369781** [comment]
If it is activated all the time, I think the max range can be reduced to about 300, It only improves the self-rescue ability of the bot when surrounded, instead of having them kill any infected on sight.

**Comment by smilz0** [comment]
The Range is configurable by changing the "manual_attack_radius" setting. I added "manual_attack_always" so the people can choose if they want your aiming function to be always active or only when executing the orders. It's 0 by default, 1 for expert difficulty. Let me know if there is any issue with it.
I tested them on Dark Center Expert and i can tell there is a huge difference. Good job man!

**Comment by smilz0** [comment]
Hey, i'm closing this so it will appear in the changelog of the next release.
Thanks again
