### ISSUE TITLE
improve search "tank_rock"

### ISSUE THREAD

**Issue by 4512369781** [smilz0/Left4Bots#56]
Use "ability_use" events to find "rock", so we can remove it from "Left4Bots.OnThinker".

[left4bots_afterload_rock.zip](https://github.com/smilz0/Left4Bots/files/13208640/left4bots_afterload_rock.zip)

**Comment by smilz0** [comment]
I use that event in L4B1. This is better than mine because you get the rock from the move childs, i just search for a rock nearby however i think the OnThinker approach is better because it runs every frame so the think function is attached the very first frame the rock is spawned. I don't think the OnThinker function is so heavy after all, it can probably stay.

**Comment by 4512369781** [comment]
I know, I'll close this issue.
